const { Router } = require('express')
const usuarios = require('./Usuarios')
const productos = require('./Productos')
const tipos = require('./Tipos')
const hola = require('./Hola')
const paypal = require('./Paypal')
const router = Router()
const admin = require('./Admin')
router.use('/', hola)
router.use('/Usuarios', usuarios)
router.use('/Paypal', paypal)
router.use('/Productos', productos)
router.use('/Tipos', tipos)
router.use('/Admin', admin)
module.exports = router
